export const sourceNamesInZH = {
    pboc: '中国人民银行',
    unionpay: '银联',
    mastercard: 'MasterCard',
    wise: 'Wise',
    visa: 'Visa',
    jcb: 'JCB',
    abc: '中国农业银行',
    cmb: '招商银行',
    icbc: '中国工商银行',
    boc: '中国银行',
    ccb: '中国建设银行',
    psbc: '邮政储蓄银行',
    bocom: '交通银行',
    cibHuanyu: '兴业银行寰宇人生',
    cib: '兴业银行',
    'hsbc.cn': '汇丰中国',
    'hsbc.hk': '汇丰香港',
    'hsbc.au': '汇丰澳洲',
    'citic.cn': '中信银行',
    spdb: '浦发银行',
    'ncb.cn': '南洋商业银行（中国）',
    xib: '厦门国际银行',
    pab: '平安银行',
    ceb: '中国光大银行',
};
